/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Parky (void)
{
  GtkWidget *Parky;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *entry_id;
  GtkWidget *entry_Nom;
  GtkWidget *entry_pre;
  GtkWidget *entry_em;
  GtkWidget *entry_tp;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *checkbutton1;
  GtkWidget *label6;
  GtkWidget *Homme;
  GSList *Homme_group = NULL;
  GtkWidget *Femme;
  GtkWidget *Aj;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label12;
  GtkWidget *label1;
  GtkWidget *fixed3;
  GtkWidget *entry_nvid;
  GtkWidget *entry_nvnm;
  GtkWidget *entry_nvem;
  GtkWidget *entry_nvpr;
  GtkWidget *entry_nvtp;
  GtkWidget *label19;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *Femme1;
  GSList *Femme1_group = NULL;
  GtkWidget *Homme1;
  GtkWidget *comboboxentry1;
  GtkWidget *act1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label20;
  GtkWidget *label13;
  GtkWidget *Md;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label21;
  GtkWidget *label2;
  GtkWidget *fixed4;
  GtkWidget *label22;
  GtkWidget *comboboxentry2;
  GtkWidget *Sup;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label24;
  GtkWidget *act2;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label23;
  GtkWidget *label3;
  GtkWidget *fixed5;
  GtkWidget *label32;
  GtkWidget *label29;
  GtkWidget *label28;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *nm;
  GtkWidget *pr;
  GtkWidget *em;
  GtkWidget *tp;
  GtkWidget *sx;
  GtkWidget *label25;
  GtkWidget *comboboxentry3;
  GtkWidget *act3;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label26;
  GtkWidget *Aff;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label42;
  GtkWidget *label4;
  GtkWidget *fixed6;
  GtkWidget *treeview1;
  GtkWidget *act4;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label40;
  GtkWidget *AcRes;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label41;
  GtkWidget *comboboxentry4;
  GtkWidget *label39;
  GtkWidget *label5;

  Parky = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Parky), _("Parky"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Parky), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 550, 500);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id, 136, 72);
  gtk_widget_set_size_request (entry_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_Nom = gtk_entry_new ();
  gtk_widget_show (entry_Nom);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_Nom, 136, 120);
  gtk_widget_set_size_request (entry_Nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Nom), 8226);

  entry_pre = gtk_entry_new ();
  gtk_widget_show (entry_pre);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_pre, 136, 168);
  gtk_widget_set_size_request (entry_pre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_pre), 8226);

  entry_em = gtk_entry_new ();
  gtk_widget_show (entry_em);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_em, 136, 216);
  gtk_widget_set_size_request (entry_em, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_em), 8226);

  entry_tp = gtk_entry_new ();
  gtk_widget_show (entry_tp);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_tp, 136, 264);
  gtk_widget_set_size_request (entry_tp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_tp), 8226);

  label7 = gtk_label_new (_("Nom"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 32, 112);
  gtk_widget_set_size_request (label7, 80, 41);

  label8 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 32, 168);
  gtk_widget_set_size_request (label8, 88, 33);

  label9 = gtk_label_new (_("Email"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 32, 208);
  gtk_widget_set_size_request (label9, 80, 41);

  label10 = gtk_label_new (_("Type"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 32, 256);
  gtk_widget_set_size_request (label10, 72, 33);

  label11 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 40, 304);
  gtk_widget_set_size_request (label11, 64, 23);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("J'accepte tous les conditions"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1, 72, 352);
  gtk_widget_set_size_request (checkbutton1, 240, 24);

  label6 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 8, 64);
  gtk_widget_set_size_request (label6, 160, 49);

  Homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (Homme);
  gtk_fixed_put (GTK_FIXED (fixed2), Homme, 136, 304);
  gtk_widget_set_size_request (Homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Homme), Homme_group);
  Homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Homme));

  Femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (Femme);
  gtk_fixed_put (GTK_FIXED (fixed2), Femme, 264, 304);
  gtk_widget_set_size_request (Femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Femme), Homme_group);
  Homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Femme));

  Aj = gtk_button_new ();
  gtk_widget_show (Aj);
  gtk_fixed_put (GTK_FIXED (fixed2), Aj, 328, 344);
  gtk_widget_set_size_request (Aj, 104, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Aj), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox1), label12, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("<span foreground=\"navy\">Ajouter</span>"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry_nvid = gtk_entry_new ();
  gtk_widget_show (entry_nvid);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_nvid, 224, 80);
  gtk_widget_set_size_request (entry_nvid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nvid), 8226);

  entry_nvnm = gtk_entry_new ();
  gtk_widget_show (entry_nvnm);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_nvnm, 224, 120);
  gtk_widget_set_size_request (entry_nvnm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nvnm), 8226);

  entry_nvem = gtk_entry_new ();
  gtk_widget_show (entry_nvem);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_nvem, 224, 216);
  gtk_widget_set_size_request (entry_nvem, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nvem), 8226);

  entry_nvpr = gtk_entry_new ();
  gtk_widget_show (entry_nvpr);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_nvpr, 224, 168);
  gtk_widget_set_size_request (entry_nvpr, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nvpr), 8226);

  entry_nvtp = gtk_entry_new ();
  gtk_widget_show (entry_nvtp);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_nvtp, 224, 264);
  gtk_widget_set_size_request (entry_nvtp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nvtp), 8226);

  label19 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 5, 64);
  gtk_widget_set_size_request (label19, 160, 49);

  label14 = gtk_label_new (_("Nom"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 32, 112);
  gtk_widget_set_size_request (label14, 80, 41);

  label15 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 32, 160);
  gtk_widget_set_size_request (label15, 88, 33);

  label16 = gtk_label_new (_("Email"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 32, 208);
  gtk_widget_set_size_request (label16, 80, 41);

  label17 = gtk_label_new (_("Type"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 32, 256);
  gtk_widget_set_size_request (label17, 72, 33);

  label18 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 40, 304);
  gtk_widget_set_size_request (label18, 64, 23);

  Femme1 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (Femme1);
  gtk_fixed_put (GTK_FIXED (fixed3), Femme1, 248, 304);
  gtk_widget_set_size_request (Femme1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Femme1), Femme1_group);
  Femme1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Femme1));

  Homme1 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (Homme1);
  gtk_fixed_put (GTK_FIXED (fixed3), Homme1, 120, 304);
  gtk_widget_set_size_request (Homme1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Homme1), Femme1_group);
  Femme1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Homme1));

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry1, 216, 24);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);

  act1 = gtk_button_new ();
  gtk_widget_show (act1);
  gtk_fixed_put (GTK_FIXED (fixed3), act1, 432, 24);
  gtk_widget_set_size_request (act1, 96, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (act1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox2), label20, FALSE, FALSE, 0);

  label13 = gtk_label_new (_("<u> <span font_size=\"11000\">selectionner l'ID pour modifier :</span></u>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 0, 24);
  gtk_widget_set_size_request (label13, 200, 24);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  Md = gtk_button_new ();
  gtk_widget_show (Md);
  gtk_fixed_put (GTK_FIXED (fixed3), Md, 440, 384);
  gtk_widget_set_size_request (Md, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Md), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\">Modifier</span>\n"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox3), label21, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  label2 = gtk_label_new (_("<span foreground=\"navy\">Modifier</span>"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  label22 = gtk_label_new (_("<u> <span font_size=\"11000\">selectionner l'ID pour supprimer :</span></u>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 0, 48);
  gtk_widget_set_size_request (label22, 216, 24);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxentry2, 232, 48);
  gtk_widget_set_size_request (comboboxentry2, 189, 29);

  Sup = gtk_button_new ();
  gtk_widget_show (Sup);
  gtk_fixed_put (GTK_FIXED (fixed4), Sup, 440, 144);
  gtk_widget_set_size_request (Sup, 104, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (Sup), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\">Supprimer</span>\n"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  act2 = gtk_button_new ();
  gtk_widget_show (act2);
  gtk_fixed_put (GTK_FIXED (fixed4), act2, 440, 48);
  gtk_widget_set_size_request (act2, 104, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (act2), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox4), label23, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("<span foreground=\"navy\">Supprimer</span>"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  label32 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 40, 344);
  gtk_widget_set_size_request (label32, 64, 23);

  label29 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 32, 160);
  gtk_widget_set_size_request (label29, 88, 33);

  label28 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 40, 96);
  gtk_widget_set_size_request (label28, 80, 41);

  label30 = gtk_label_new (_("Email :"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 32, 216);
  gtk_widget_set_size_request (label30, 80, 41);

  label31 = gtk_label_new (_("Type :"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 40, 280);
  gtk_widget_set_size_request (label31, 72, 33);

  nm = gtk_label_new ("");
  gtk_widget_show (nm);
  gtk_fixed_put (GTK_FIXED (fixed5), nm, 120, 96);
  gtk_widget_set_size_request (nm, 168, 40);

  pr = gtk_label_new ("");
  gtk_widget_show (pr);
  gtk_fixed_put (GTK_FIXED (fixed5), pr, 120, 152);
  gtk_widget_set_size_request (pr, 168, 40);

  em = gtk_label_new ("");
  gtk_widget_show (em);
  gtk_fixed_put (GTK_FIXED (fixed5), em, 96, 216);
  gtk_widget_set_size_request (em, 216, 40);

  tp = gtk_label_new ("");
  gtk_widget_show (tp);
  gtk_fixed_put (GTK_FIXED (fixed5), tp, 120, 280);
  gtk_widget_set_size_request (tp, 168, 40);

  sx = gtk_label_new ("");
  gtk_widget_show (sx);
  gtk_fixed_put (GTK_FIXED (fixed5), sx, 120, 336);
  gtk_widget_set_size_request (sx, 168, 40);

  label25 = gtk_label_new (_("<u> <span font_size=\"11000\">selectionner l'ID pour afficher :</span></u>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 0, 32);
  gtk_widget_set_size_request (label25, 216, 24);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentry3, 232, 32);
  gtk_widget_set_size_request (comboboxentry3, 189, 29);

  act3 = gtk_button_new ();
  gtk_widget_show (act3);
  gtk_fixed_put (GTK_FIXED (fixed5), act3, 440, 32);
  gtk_widget_set_size_request (act3, 96, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (act3), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox6), label26, FALSE, FALSE, 0);

  Aff = gtk_button_new ();
  gtk_widget_show (Aff);
  gtk_fixed_put (GTK_FIXED (fixed5), Aff, 432, 392);
  gtk_widget_set_size_request (Aff, 96, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (Aff), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("<span foreground=\"Blue\">Afficher</span>\n"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox9), label42, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  label4 = gtk_label_new (_("<span foreground=\"navy\">Afficher</span>"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview1, 0, 112);
  gtk_widget_set_size_request (treeview1, 552, 360);

  act4 = gtk_button_new ();
  gtk_widget_show (act4);
  gtk_fixed_put (GTK_FIXED (fixed6), act4, 272, 56);
  gtk_widget_set_size_request (act4, 96, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (act4), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox7), label40, FALSE, FALSE, 0);

  AcRes = gtk_button_new ();
  gtk_widget_show (AcRes);
  gtk_fixed_put (GTK_FIXED (fixed6), AcRes, 392, 56);
  gtk_widget_set_size_request (AcRes, 88, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (AcRes), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\">Acc\303\251der</span>\n\n"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox8), label41, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry4, 64, 56);
  gtk_widget_set_size_request (comboboxentry4, 189, 29);

  label39 = gtk_label_new (_("<u> <span font_size=\"11000\">selectionner la date  :</span></u>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 88, 8);
  gtk_widget_set_size_request (label39, 144, 33);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  label5 = gtk_label_new (_("<span foreground=\"navy\">Reservation</span>"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label5);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  g_signal_connect ((gpointer) Homme, "toggled",
                    G_CALLBACK (on_Homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) Femme, "toggled",
                    G_CALLBACK (on_Femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) Aj, "clicked",
                    G_CALLBACK (on_Aj_clicked),
                    NULL);
  g_signal_connect ((gpointer) Femme1, "toggled",
                    G_CALLBACK (on_Femme1_toggled),
                    NULL);
  g_signal_connect ((gpointer) Homme1, "toggled",
                    G_CALLBACK (on_Homme1_toggled),
                    NULL);
  g_signal_connect ((gpointer) act1, "clicked",
                    G_CALLBACK (on_act1_clicked),
                    NULL);
  g_signal_connect ((gpointer) Md, "clicked",
                    G_CALLBACK (on_Md_clicked),
                    NULL);
  g_signal_connect ((gpointer) Sup, "clicked",
                    G_CALLBACK (on_Sup_clicked),
                    NULL);
  g_signal_connect ((gpointer) act2, "clicked",
                    G_CALLBACK (on_act2_clicked),
                    NULL);
  g_signal_connect ((gpointer) act3, "clicked",
                    G_CALLBACK (on_act3_clicked),
                    NULL);
  g_signal_connect ((gpointer) Aff, "clicked",
                    G_CALLBACK (on_Aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) act4, "clicked",
                    G_CALLBACK (on_act4_clicked),
                    NULL);
  g_signal_connect ((gpointer) AcRes, "clicked",
                    G_CALLBACK (on_AcRes_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Parky, Parky, "Parky");
  GLADE_HOOKUP_OBJECT (Parky, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Parky, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Parky, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Parky, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (Parky, entry_Nom, "entry_Nom");
  GLADE_HOOKUP_OBJECT (Parky, entry_pre, "entry_pre");
  GLADE_HOOKUP_OBJECT (Parky, entry_em, "entry_em");
  GLADE_HOOKUP_OBJECT (Parky, entry_tp, "entry_tp");
  GLADE_HOOKUP_OBJECT (Parky, label7, "label7");
  GLADE_HOOKUP_OBJECT (Parky, label8, "label8");
  GLADE_HOOKUP_OBJECT (Parky, label9, "label9");
  GLADE_HOOKUP_OBJECT (Parky, label10, "label10");
  GLADE_HOOKUP_OBJECT (Parky, label11, "label11");
  GLADE_HOOKUP_OBJECT (Parky, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (Parky, label6, "label6");
  GLADE_HOOKUP_OBJECT (Parky, Homme, "Homme");
  GLADE_HOOKUP_OBJECT (Parky, Femme, "Femme");
  GLADE_HOOKUP_OBJECT (Parky, Aj, "Aj");
  GLADE_HOOKUP_OBJECT (Parky, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Parky, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Parky, image1, "image1");
  GLADE_HOOKUP_OBJECT (Parky, label12, "label12");
  GLADE_HOOKUP_OBJECT (Parky, label1, "label1");
  GLADE_HOOKUP_OBJECT (Parky, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Parky, entry_nvid, "entry_nvid");
  GLADE_HOOKUP_OBJECT (Parky, entry_nvnm, "entry_nvnm");
  GLADE_HOOKUP_OBJECT (Parky, entry_nvem, "entry_nvem");
  GLADE_HOOKUP_OBJECT (Parky, entry_nvpr, "entry_nvpr");
  GLADE_HOOKUP_OBJECT (Parky, entry_nvtp, "entry_nvtp");
  GLADE_HOOKUP_OBJECT (Parky, label19, "label19");
  GLADE_HOOKUP_OBJECT (Parky, label14, "label14");
  GLADE_HOOKUP_OBJECT (Parky, label15, "label15");
  GLADE_HOOKUP_OBJECT (Parky, label16, "label16");
  GLADE_HOOKUP_OBJECT (Parky, label17, "label17");
  GLADE_HOOKUP_OBJECT (Parky, label18, "label18");
  GLADE_HOOKUP_OBJECT (Parky, Femme1, "Femme1");
  GLADE_HOOKUP_OBJECT (Parky, Homme1, "Homme1");
  GLADE_HOOKUP_OBJECT (Parky, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (Parky, act1, "act1");
  GLADE_HOOKUP_OBJECT (Parky, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Parky, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Parky, image2, "image2");
  GLADE_HOOKUP_OBJECT (Parky, label20, "label20");
  GLADE_HOOKUP_OBJECT (Parky, label13, "label13");
  GLADE_HOOKUP_OBJECT (Parky, Md, "Md");
  GLADE_HOOKUP_OBJECT (Parky, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Parky, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Parky, image3, "image3");
  GLADE_HOOKUP_OBJECT (Parky, label21, "label21");
  GLADE_HOOKUP_OBJECT (Parky, label2, "label2");
  GLADE_HOOKUP_OBJECT (Parky, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Parky, label22, "label22");
  GLADE_HOOKUP_OBJECT (Parky, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (Parky, Sup, "Sup");
  GLADE_HOOKUP_OBJECT (Parky, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Parky, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Parky, image5, "image5");
  GLADE_HOOKUP_OBJECT (Parky, label24, "label24");
  GLADE_HOOKUP_OBJECT (Parky, act2, "act2");
  GLADE_HOOKUP_OBJECT (Parky, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Parky, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Parky, image4, "image4");
  GLADE_HOOKUP_OBJECT (Parky, label23, "label23");
  GLADE_HOOKUP_OBJECT (Parky, label3, "label3");
  GLADE_HOOKUP_OBJECT (Parky, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Parky, label32, "label32");
  GLADE_HOOKUP_OBJECT (Parky, label29, "label29");
  GLADE_HOOKUP_OBJECT (Parky, label28, "label28");
  GLADE_HOOKUP_OBJECT (Parky, label30, "label30");
  GLADE_HOOKUP_OBJECT (Parky, label31, "label31");
  GLADE_HOOKUP_OBJECT (Parky, nm, "nm");
  GLADE_HOOKUP_OBJECT (Parky, pr, "pr");
  GLADE_HOOKUP_OBJECT (Parky, em, "em");
  GLADE_HOOKUP_OBJECT (Parky, tp, "tp");
  GLADE_HOOKUP_OBJECT (Parky, sx, "sx");
  GLADE_HOOKUP_OBJECT (Parky, label25, "label25");
  GLADE_HOOKUP_OBJECT (Parky, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (Parky, act3, "act3");
  GLADE_HOOKUP_OBJECT (Parky, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Parky, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Parky, image6, "image6");
  GLADE_HOOKUP_OBJECT (Parky, label26, "label26");
  GLADE_HOOKUP_OBJECT (Parky, Aff, "Aff");
  GLADE_HOOKUP_OBJECT (Parky, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Parky, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Parky, image9, "image9");
  GLADE_HOOKUP_OBJECT (Parky, label42, "label42");
  GLADE_HOOKUP_OBJECT (Parky, label4, "label4");
  GLADE_HOOKUP_OBJECT (Parky, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Parky, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Parky, act4, "act4");
  GLADE_HOOKUP_OBJECT (Parky, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Parky, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Parky, image7, "image7");
  GLADE_HOOKUP_OBJECT (Parky, label40, "label40");
  GLADE_HOOKUP_OBJECT (Parky, AcRes, "AcRes");
  GLADE_HOOKUP_OBJECT (Parky, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Parky, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Parky, image8, "image8");
  GLADE_HOOKUP_OBJECT (Parky, label41, "label41");
  GLADE_HOOKUP_OBJECT (Parky, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (Parky, label39, "label39");
  GLADE_HOOKUP_OBJECT (Parky, label5, "label5");

  return Parky;
}

